### ISSUE TITLE
Feature request: RSS feed for posts

### ISSUE THREAD

**Issue by wezm** [itehax/itehax_website#1]
Would be great to be able to subscribe to your blog in an RSS reader.

**Comment by itehax** [comment]
Sorry for the delay in replying,it has been a bit busy days :).
Definitely,thanks for the idea,I will definitely add this feature.

**Comment by itehax** [comment]
> Would be great to be able to subscribe to your blog in an RSS reader.

Hello! Just added in case you are interested :)

**Comment by wezm** [comment]
Thank you! I've subscribed now and it's working well.
